# /Users/fhsshim/.config/tmuxinator/default.yml
name: default
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim: nvim
        - monitor: htop
        - terminal: #empty
